# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddForm(object):
    def setupUi(self, AddForm):
        AddForm.setObjectName("AddForm")
        AddForm.resize(471, 352)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        AddForm.setFont(font)
        self.label = QtWidgets.QLabel(AddForm)
        self.label.setGeometry(QtCore.QRect(40, 40, 71, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.url_field = QtWidgets.QLineEdit(AddForm)
        self.url_field.setGeometry(QtCore.QRect(110, 40, 311, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.url_field.setFont(font)
        self.url_field.setObjectName("url_field")
        self.label_2 = QtWidgets.QLabel(AddForm)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.uname_field = QtWidgets.QLineEdit(AddForm)
        self.uname_field.setGeometry(QtCore.QRect(40, 130, 381, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.uname_field.setFont(font)
        self.uname_field.setObjectName("uname_field")
        self.label_3 = QtWidgets.QLabel(AddForm)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 141, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pwd_field = QtWidgets.QLineEdit(AddForm)
        self.pwd_field.setGeometry(QtCore.QRect(40, 230, 381, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.pwd_field.setFont(font)
        self.pwd_field.setObjectName("pwd_field")
        self.submitBtn = QtWidgets.QPushButton(AddForm)
        self.submitBtn.setGeometry(QtCore.QRect(40, 290, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        self.submitBtn.setFont(font)
        self.submitBtn.setObjectName("submitBtn")
        self.cancleBtn = QtWidgets.QPushButton(AddForm)
        self.cancleBtn.setGeometry(QtCore.QRect(320, 290, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        self.cancleBtn.setFont(font)
        self.cancleBtn.setObjectName("cancleBtn")

        self.retranslateUi(AddForm)
        QtCore.QMetaObject.connectSlotsByName(AddForm)

    def retranslateUi(self, AddForm):
        _translate = QtCore.QCoreApplication.translate
        AddForm.setWindowTitle(_translate("AddForm", "添加新的链接"))
        self.label.setText(_translate("AddForm", "URL："))
        self.url_field.setPlaceholderText(_translate("AddForm", "在这里输入URL"))
        self.label_2.setText(_translate("AddForm", "UserName："))
        self.uname_field.setPlaceholderText(_translate("AddForm", "在这里输入用户名"))
        self.label_3.setText(_translate("AddForm", "PassWord："))
        self.pwd_field.setPlaceholderText(_translate("AddForm", "在这里输入密码"))
        self.submitBtn.setText(_translate("AddForm", "提交"))
        self.cancleBtn.setText(_translate("AddForm", "取消"))
